# Generated by Django 5.2.12 on 2026-03-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_cidade_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cargo_chefia',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo da chefia'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='coordenador_adm_plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Coordenador administrativo padrão (Plano de Trabalho)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='nome_chefia',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome da chefia'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_ano',
            field=models.PositiveIntegerField(default=0, verbose_name='Ano vigente PT'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_ultimo_numero',
            field=models.PositiveIntegerField(default=0, verbose_name='Último número PT (ano vigente)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='assinaturaconfiguracao',
            name='tipo',
            field=models.CharField(choices=[('OFICIO', 'Ofício'), ('JUSTIFICATIVA', 'Justificativa'), ('PLANO_TRABALHO', 'Plano de Trabalho'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('TERMO_AUTORIZACAO', 'Termo de Autorização')], max_length=20, verbose_name='Tipo'),
        ),
    ]
