# Generated by Django 6.0.1 on 2026-03-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_cidade_latitude_longitude'),
        ('eventos', '0015_oficio_porte_transporte_armas'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='cidade_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede', to='cadastros.cidade', verbose_name='Cidade sede'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='estado_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede', to='cadastros.estado', verbose_name='Estado sede'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_cidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Retorno - cidade de chegada'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_data',
            field=models.DateField(blank=True, null=True, verbose_name='Retorno - data de chegada'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_chegada_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Retorno - hora de chegada'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_cidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Retorno - cidade de saída'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_data',
            field=models.DateField(blank=True, null=True, verbose_name='Retorno - data de saída'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_saida_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Retorno - hora de saída'),
        ),
        migrations.CreateModel(
            name='OficioTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('saida_data', models.DateField(blank=True, null=True, verbose_name='Saída - data')),
                ('saida_hora', models.TimeField(blank=True, null=True, verbose_name='Saída - hora')),
                ('chegada_data', models.DateField(blank=True, null=True, verbose_name='Chegada - data')),
                ('chegada_hora', models.TimeField(blank=True, null=True, verbose_name='Chegada - hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_trechos_destino', to='cadastros.cidade', verbose_name='Cidade destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_trechos_destino', to='cadastros.estado', verbose_name='Estado destino')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='eventos.oficio', verbose_name='Ofício')),
                ('origem_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_trechos_origem', to='cadastros.cidade', verbose_name='Cidade origem')),
                ('origem_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_trechos_origem', to='cadastros.estado', verbose_name='Estado origem')),
            ],
            options={
                'verbose_name': 'Trecho do ofício',
                'verbose_name_plural': 'Trechos do ofício',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('oficio', 'ordem'), name='eventos_oficiotrecho_oficio_ordem_unique')],
            },
        ),
    ]
