# Generated by Django 6.0.1 on 2026-03-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_oficio_cidade_sede_oficio_estado_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='quantidade_diarias',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Quantidade de diárias'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='eventos.roteiroevento', verbose_name='Roteiro do evento selecionado'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro_modo',
            field=models.CharField(blank=True, choices=[('EVENTO_EXISTENTE', 'Usar roteiro existente do evento'), ('ROTEIRO_PROPRIO', 'Criar novo roteiro para este ofício')], default='ROTEIRO_PROPRIO', max_length=20, verbose_name='Modo do roteiro'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='valor_diarias',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Valor das diárias'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='valor_diarias_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Valor das diárias por extenso'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota calculada em'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Fonte da rota'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='oficiotrecho',
            name='tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo cru estimado (min)'),
        ),
    ]
