# Generated by Django 6.0.1 on 2026-03-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_oficio_quantidade_diarias_oficio_roteiro_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do modelo')),
                ('texto', models.TextField(verbose_name='Texto da justificativa')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de justificativa',
                'verbose_name_plural': 'Modelos de justificativa',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='justificativa_texto',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='justificativa_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='eventos.modelojustificativa', verbose_name='Modelo de justificativa'),
        ),
    ]
