# Generated by Django 6.0.1 on 2026-03-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_modelojustificativa_oficio_justificativa_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFundamentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_fundamentacao', models.TextField(blank=True, default='', help_text='Fundamentação do evento para fins de PT-OS (Plano de Trabalho / Ordem de Serviço).', verbose_name='Texto da fundamentação')),
                ('observacoes_pt_os', models.TextField(blank=True, default='', verbose_name='Observações (PT-OS)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentacao', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Fundamentação do evento',
                'verbose_name_plural': 'Fundamentações do evento',
            },
        ),
    ]
