# Generated by Django 6.0.1 on 2026-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_eventofinalizacao_etapa6'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotermoparticipante',
            name='modalidade',
            field=models.CharField(
                choices=[('COMPLETO', 'Completo'), ('SEMIPREENCHIDO', 'Semipreenchido')],
                default='COMPLETO',
                max_length=20,
                verbose_name='Modalidade do termo',
            ),
        ),
        migrations.AddField(
            model_name='eventotermoparticipante',
            name='ultima_geracao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última geração em'),
        ),
        migrations.AddField(
            model_name='eventotermoparticipante',
            name='ultimo_formato_gerado',
            field=models.CharField(
                blank=True,
                choices=[('docx', 'DOCX'), ('pdf', 'PDF')],
                default='',
                max_length=10,
                verbose_name='Último formato gerado',
            ),
        ),
        migrations.AlterField(
            model_name='eventotermoparticipante',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('DISPENSADO', 'Dispensado'),
                    ('GERADO', 'Gerado'),
                    ('CONCLUIDO', 'Concluído'),
                ],
                default='PENDENTE',
                max_length=20,
                verbose_name='Status do termo',
            ),
        ),
    ]
