# Generated by Django 5.2.12 on 2026-03-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0023_eventotermoparticipante_modalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo')),
                ('cidade', models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade')),
                ('unidade', models.CharField(blank=True, default='', max_length=160, verbose_name='Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coordenador operacional',
                'verbose_name_plural': 'Coordenadores operacionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitantePlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('is_padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitante (Plano de Trabalho)',
                'verbose_name_plural': 'Solicitantes (Plano de Trabalho)',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='atividades_codigos',
            field=models.CharField(blank=True, default='', help_text='Códigos separados por vírgula, ex: CIN,BO,NOC', max_length=500, verbose_name='Atividades (códigos)'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='coordenador_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamentacoes_pt_coord_adm', to='cadastros.viajante', verbose_name='Coordenador administrativo'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='horario_atendimento',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Horário de atendimento'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='recursos_texto',
            field=models.TextField(blank=True, default='', help_text='Estrutura para {{recursos_formatado}}; regra final pendente.', verbose_name='Recursos (texto)'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='solicitante_outros',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Solicitante (outros)'),
        ),
        migrations.AlterField(
            model_name='eventofundamentacao',
            name='texto_fundamentacao',
            field=models.TextField(blank=True, default='', help_text='Fundamentação do evento para fins de Plano de Trabalho ou Ordem de Serviço.', verbose_name='Texto da fundamentação'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='coordenador_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamentacoes_pt', to='eventos.coordenadoroperacional', verbose_name='Coordenador operacional'),
        ),
        migrations.AddField(
            model_name='eventofundamentacao',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamentacoes_pt', to='eventos.solicitanteplanotrabalho', verbose_name='Solicitante (PT)'),
        ),
        migrations.CreateModel(
            name='EfetivoPlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_plano', to='cadastros.cargo', verbose_name='Cargo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivo_plano_trabalho', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Efetivo (Plano de Trabalho)',
                'verbose_name_plural': 'Efetivos (Plano de Trabalho)',
                'ordering': ['evento', 'cargo__nome'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'cargo'), name='eventos_efetivoplano_evento_cargo_unique')],
            },
        ),
    ]
