# Generated by Django 5.2.12 on 2026-03-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_roteiroevento_avulso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roteiroevento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Roteiro', 'verbose_name_plural': 'Roteiros'},
        ),
        migrations.CreateModel(
            name='DocumentoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Ofício avulso'), ('TERMO_AUTORIZACAO', 'Termo de autorização avulso'), ('JUSTIFICATIVA', 'Justificativa avulsa'), ('PLANO_TRABALHO', 'Plano de trabalho avulso'), ('ORDEM_SERVICO', 'Ordem de serviço avulsa'), ('OUTRO', 'Outros modelos avulsos')], max_length=30, verbose_name='Tipo do documento')),
                ('conteudo_texto', models.TextField(blank=True, default='', verbose_name='Conteúdo livre')),
                ('placeholders', models.JSONField(blank=True, default=dict, verbose_name='Placeholders')),
                ('termo_template_variant', models.CharField(choices=[('COMPLETO_COM_VIATURA', 'Termo completo com viatura'), ('COMPLETO_SEM_VIATURA', 'Termo completo sem viatura'), ('SEMIPREENCHIDO', 'Termo semipreenchido/manual')], default='SEMIPREENCHIDO', max_length=30, verbose_name='Variante do template de termo')),
                ('classificacao', models.CharField(choices=[('AVULSO', 'Avulso'), ('VINCULADO', 'Vinculado')], db_index=True, default='AVULSO', max_length=20, verbose_name='Classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.evento', verbose_name='Evento vinculado')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.oficio', verbose_name='Ofício vinculado')),
                ('plano_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.eventofundamentacao', verbose_name='Plano de trabalho / OS vinculado')),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.roteiroevento', verbose_name='Roteiro vinculado')),
            ],
            options={
                'verbose_name': 'Documento avulso',
                'verbose_name_plural': 'Documentos avulsos',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
