# Generated by Django 6.0.1 on 2026-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_oficio_tipo_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='retorno_distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Retorno - distancia (km)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno - duracao estimada (min)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno - rota calculada em'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_rota_fonte',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Retorno - fonte da rota'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Retorno - tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='retorno_tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno - tempo cru estimado (min)'),
        ),
    ]
