# Generated by Django 6.0.1 on 2026-03-18 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _status_from_fundamentacao(tipo_documento, texto_fundamentacao):
    tipo_ok = bool((tipo_documento or '').strip())
    texto_ok = bool((texto_fundamentacao or '').strip())
    return 'FINALIZADO' if (tipo_ok and texto_ok) else 'RASCUNHO'


def migrate_fundamentacao_to_pt_os(apps, schema_editor):
    EventoFundamentacao = apps.get_model('eventos', 'EventoFundamentacao')
    PlanoTrabalho = apps.get_model('eventos', 'PlanoTrabalho')
    OrdemServico = apps.get_model('eventos', 'OrdemServico')
    DocumentoAvulso = apps.get_model('eventos', 'DocumentoAvulso')
    EfetivoPlanoTrabalho = apps.get_model('eventos', 'EfetivoPlanoTrabalho')
    EfetivoPlanoTrabalhoDocumento = apps.get_model('eventos', 'EfetivoPlanoTrabalhoDocumento')

    fundamentacoes = list(EventoFundamentacao.objects.all().iterator())
    pt_ids = set()
    os_ids = set()
    pt_by_evento = {}

    for fundamentacao in fundamentacoes:
        tipo_documento = (fundamentacao.tipo_documento or '').strip().upper()
        status = _status_from_fundamentacao(tipo_documento, fundamentacao.texto_fundamentacao)
        data_criacao = None
        if fundamentacao.created_at:
            data_criacao = fundamentacao.created_at.date()

        if tipo_documento == 'OS':
            OrdemServico.objects.update_or_create(
                id=fundamentacao.id,
                defaults={
                    'evento_id': fundamentacao.evento_id,
                    'numero': None,
                    'ano': None,
                    'data_criacao': data_criacao,
                    'status': status,
                    'finalidade': fundamentacao.texto_fundamentacao or '',
                    'observacoes': fundamentacao.observacoes_pt_os or '',
                },
            )
            os_ids.add(fundamentacao.id)
            continue

        PlanoTrabalho.objects.update_or_create(
            id=fundamentacao.id,
            defaults={
                'evento_id': fundamentacao.evento_id,
                'numero': None,
                'ano': None,
                'data_criacao': data_criacao,
                'status': status,
                'solicitante_id': fundamentacao.solicitante_id,
                'solicitante_outros': fundamentacao.solicitante_outros or '',
                'coordenador_operacional_id': fundamentacao.coordenador_operacional_id,
                'coordenador_administrativo_id': fundamentacao.coordenador_administrativo_id,
                'objetivo': fundamentacao.texto_fundamentacao or '',
                'horario_atendimento': fundamentacao.horario_atendimento or '',
                'atividades_codigos': fundamentacao.atividades_codigos or '',
                'recursos_texto': fundamentacao.recursos_texto or '',
                'observacoes': fundamentacao.observacoes_pt_os or '',
            },
        )
        pt_ids.add(fundamentacao.id)
        if fundamentacao.evento_id:
            pt_by_evento[fundamentacao.evento_id] = fundamentacao.id

    # O vínculo legado de DocumentoAvulso.plano_trabalho apontava para EventoFundamentacao.
    # IDs de fundamentações OS devem ir para o novo campo ordem_servico.
    if os_ids:
        DocumentoAvulso.objects.filter(plano_trabalho_id__in=os_ids).update(
            ordem_servico_id=models.F('plano_trabalho_id'),
            plano_trabalho_id=None,
        )

    # IDs órfãos não mapeados em PT/OS devem ser limpos para evitar FK inválida.
    ids_validos = pt_ids | os_ids
    if ids_validos:
        DocumentoAvulso.objects.exclude(plano_trabalho_id__isnull=True).exclude(
            plano_trabalho_id__in=ids_validos
        ).update(plano_trabalho_id=None)
    else:
        DocumentoAvulso.objects.exclude(plano_trabalho_id__isnull=True).update(plano_trabalho_id=None)

    # Migra o efetivo legado por evento para o efetivo do documento PT.
    for efetivo in EfetivoPlanoTrabalho.objects.select_related('evento').all().iterator():
        plano_trabalho_id = pt_by_evento.get(efetivo.evento_id)
        if not plano_trabalho_id:
            continue
        EfetivoPlanoTrabalhoDocumento.objects.update_or_create(
            plano_trabalho_id=plano_trabalho_id,
            cargo_id=efetivo.cargo_id,
            defaults={'quantidade': efetivo.quantidade},
        )


def noop_reverse(apps, schema_editor):
    # Não desfaz automaticamente para evitar perda dos dados já migrados.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0030_alter_oficio_roteiro_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano')),
                ('data_criacao', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('finalidade', models.TextField(blank=True, default='', verbose_name='Finalidade')),
                ('responsaveis', models.TextField(blank=True, default='', verbose_name='Responsáveis')),
                ('designacoes', models.TextField(blank=True, default='', verbose_name='Designações')),
                ('determinacoes', models.TextField(blank=True, default='', verbose_name='Determinações')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='eventos.evento', verbose_name='Evento')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='eventos.oficio', verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentoavulso',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.ordemservico', verbose_name='Ordem de serviço vinculada'),
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano')),
                ('data_criacao', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('solicitante_outros', models.CharField(blank=True, default='', max_length=200, verbose_name='Solicitante (outros)')),
                ('coordenador_municipal', models.CharField(blank=True, default='', max_length=200, verbose_name='Coordenador municipal')),
                ('objetivo', models.TextField(blank=True, default='', verbose_name='Objetivo/finalidade')),
                ('locais', models.TextField(blank=True, default='', verbose_name='Locais')),
                ('horario_atendimento', models.CharField(blank=True, default='', max_length=120, verbose_name='Horário de atendimento')),
                ('quantidade_servidores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de servidores')),
                ('atividades_codigos', models.CharField(blank=True, default='', max_length=500, verbose_name='Atividades (códigos)')),
                ('metas_formatadas', models.TextField(blank=True, default='', verbose_name='Metas formatadas')),
                ('efetivo_resumo', models.TextField(blank=True, default='', verbose_name='Efetivo (resumo)')),
                ('recursos_texto', models.TextField(blank=True, default='', verbose_name='Recursos (texto)')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordenador_administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho_coord_adm', to='cadastros.viajante', verbose_name='Coordenador administrativo')),
                ('coordenador_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='eventos.coordenadoroperacional', verbose_name='Coordenador operacional')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='eventos.evento', verbose_name='Evento')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='eventos.oficio', verbose_name='Ofício')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='eventos.solicitanteplanotrabalho', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Plano de trabalho',
                'verbose_name_plural': 'Planos de trabalho',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='documentoavulso',
            name='plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_avulsos', to='eventos.planotrabalho', verbose_name='Plano de trabalho vinculado'),
        ),
        migrations.CreateModel(
            name='EfetivoPlanoTrabalhoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_plano_documento', to='cadastros.cargo', verbose_name='Cargo')),
                ('plano_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='eventos.planotrabalho', verbose_name='Plano de trabalho')),
            ],
            options={
                'verbose_name': 'Efetivo do plano de trabalho',
                'verbose_name_plural': 'Efetivos do plano de trabalho',
                'ordering': ['plano_trabalho', 'cargo__nome'],
                'constraints': [models.UniqueConstraint(fields=('plano_trabalho', 'cargo'), name='eventos_efetivoptdocumento_plano_cargo_unique')],
            },
        ),
        migrations.RunPython(migrate_fundamentacao_to_pt_os, noop_reverse),
    ]
