# Generated by Django 5.2.12 on 2026-03-18 17:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_oficio_justificativa_to_model(apps, schema_editor):
    Oficio = apps.get_model('eventos', 'Oficio')
    Justificativa = apps.get_model('eventos', 'Justificativa')

    for oficio in Oficio.objects.all().iterator():
        texto = (getattr(oficio, 'justificativa_texto', '') or '').strip()
        modelo_id = getattr(oficio, 'justificativa_modelo_id', None)
        if not texto and not modelo_id:
            continue
        Justificativa.objects.update_or_create(
            oficio_id=oficio.id,
            defaults={
                'modelo_id': modelo_id,
                'texto': texto,
            },
        )


def noop_reverse(apps, schema_editor):
    # Mantém o rollback sem tentar repovoar campos legados removidos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_delete_eventofundamentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto da justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='eventos.modelojustificativa', verbose_name='Modelo de justificativa')),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa', to='eventos.oficio', verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.RunPython(migrate_oficio_justificativa_to_model, noop_reverse),
        migrations.RemoveField(
            model_name='oficio',
            name='justificativa_modelo',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='justificativa_texto',
        ),
    ]
