# Generated by Django 6.0.1 on 2026-03-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0033_remove_oficio_justificativa_modelo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_geracao', models.CharField(choices=[('RAPIDO', 'Termo rapido'), ('AUTOMATICO_COM_VIATURA', 'Automatico com viatura'), ('AUTOMATICO_SEM_VIATURA', 'Automatico sem viatura')], db_index=True, default='RAPIDO', max_length=40, verbose_name='Modo de geracao')),
                ('template_variant', models.CharField(choices=[('COMPLETO_COM_VIATURA', 'Termo completo com viatura'), ('COMPLETO_SEM_VIATURA', 'Termo completo sem viatura'), ('SEMIPREENCHIDO', 'Termo semipreenchido/manual')], default='SEMIPREENCHIDO', max_length=30, verbose_name='Template usado')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('lote_uuid', models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Lote de geracao')),
                ('destino', models.CharField(blank=True, default='', max_length=255, verbose_name='Destino')),
                ('data_evento', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('texto_complementar', models.TextField(blank=True, default='', verbose_name='Texto complementar')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('servidor_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Servidor (snapshot)')),
                ('servidor_rg', models.CharField(blank=True, default='', max_length=40, verbose_name='RG (snapshot)')),
                ('servidor_cpf', models.CharField(blank=True, default='', max_length=40, verbose_name='CPF (snapshot)')),
                ('servidor_telefone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefone (snapshot)')),
                ('servidor_lotacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Lotacao (snapshot)')),
                ('veiculo_placa', models.CharField(blank=True, default='', max_length=12, verbose_name='Placa (snapshot)')),
                ('veiculo_modelo', models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo (snapshot)')),
                ('veiculo_combustivel', models.CharField(blank=True, default='', max_length=80, verbose_name='Combustivel (snapshot)')),
                ('ultima_geracao_em', models.DateTimeField(blank=True, null=True, verbose_name='Ultima geracao em')),
                ('ultimo_formato_gerado', models.CharField(blank=True, choices=[('docx', 'DOCX'), ('pdf', 'PDF')], default='', max_length=10, verbose_name='Ultimo formato gerado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='eventos.evento', verbose_name='Evento')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='eventos.oficio', verbose_name='Oficio')),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='eventos.roteiroevento', verbose_name='Roteiro')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='cadastros.veiculo', verbose_name='Viatura')),
                ('viajante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='cadastros.viajante', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Termo de autorizacao',
                'verbose_name_plural': 'Termos de autorizacao',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
