# Generated by Django 5.2.12 on 2026-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0034_termoautorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoautorizacao',
            name='oficios',
            field=models.ManyToManyField(blank=True, related_name='termos_autorizacao_relacionados', to='eventos.oficio', verbose_name='Oficios relacionados'),
        ),
        migrations.DeleteModel(
            name='DocumentoAvulso',
        ),
    ]
